SpeakEasy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("account.urls")),
    path('courses/', include("courses.urls")),
]

account/urls.py
from django.urls import path
from account import views

app_name = 'account'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
]

courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'

urlpatterns = [
    path('', views.all_courses, name='all_courses'),
    path('<int:course_id>/', views.selected_course, name='selected_course'),
    path('topic/<int:topic_id>', views.selected_topic, name='selected_topic'),
    path('task/<int:task_id>/', views.task_detail, name='task_detail'),
    path('save_task_progress/', views.save_task_progress, name='save_task_progress'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Language Learning{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&display=swap" rel="stylesheet">
</head>
<body>
<header>
    <a class="logo" href="{% url 'account:home' %}">LingoFlow</a>
    <nav>
        <ul>
            <li><a href="{% url 'account:home' %}">Home</a></li>
            <li><a href="{% url 'courses:all_courses' %}">Courses</a></li>
            <li><a href="/contact">Contact</a></li>
            {% if request.user.is_authenticated %}
                <li><a href="#">Progress</a></li>
                <li><a href="#">Profile</a></li>
                <li><a href="{% url 'account:logout' %}">Logout</a></li>
            {% else %}
                <li><a href="{% url 'account:login' %}">Login</a></li>
                <li><a href="{% url 'account:register' %}">Register</a></li>
            {% endif %}
        </ul>
    </nav>
</header>


{% block content %}{% endblock %}

<script src="{% static 'js/script.js' %}"></script>
<footer>
    <p>&copy; 2025 LingoFlow. Learn languages with ease!</p>
</footer>
</body>
</html>