SpeakEasy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("account.urls")),
    path('courses/', include("courses.urls")),
]

account/urls.py
from django.urls import path
from account import views

app_name = 'account'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
]

courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'

urlpatterns = [
    path('', views.all_courses, name='all_courses'),
    path('<int:course_id>/', views.selected_course, name='selected_course'),
    path('topic/<int:topic_id>', views.selected_topic, name='selected_topic'),
    path('task/<int:task_id>/', views.task_detail, name='task_detail'),
    path('save_task_progress/', views.save_task_progress, name='save_task_progress'),
]

courses/models.py
from django.db import models


class Course(models.Model):
    LEVEL_CHOICES = [
        ('A1', 'A1 - Beginner'),
        ('A2', 'A2 - Elementary'),
        ('B1', 'B1 - Intermediate'),
        ('B2', 'B2 - Upper-Intermediate'),
        ('C1', 'C1 - Advanced'),
        ('C2', 'C2 - Proficient'),
    ]
    title = models.CharField(max_length=255, unique=True)
    description = models.TextField()
    difficulty = models.CharField(max_length=2, choices=LEVEL_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["difficulty"]

    def __str__(self):
        return f"{self.get_difficulty_display()} - {self.title}"


class Topic(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="topics")
    title = models.CharField(max_length=255)
    explanation = models.TextField()
    order = models.PositiveIntegerField()

    class Meta:
        ordering = ["order"]

    def __str__(self):
        return f"{self.course.title} - {self.title}"


class Task(models.Model):
    type_choices = [
        ("1", "Missed Word"),
        ("2", "Ordering"),
        ("3", "Pronunciation"),
        ("4", "Audition")
    ]
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, related_name="tasks")
    title = models.CharField(max_length=255, default=None, blank=True)
    type = models.CharField(max_length=1, choices=type_choices)
    question = models.TextField()
    sentence_without_a_word = models.TextField(blank=True)
    variants = models.JSONField(default=list, blank=True)
    missed_word = models.TextField(blank=True)
    sentence_for_ordering = models.TextField(blank=True)
    mp3 = models.FileField(upload_to="mp3/", blank=True)
    text_to_speech = models.TextField(blank=True)
    order = models.PositiveIntegerField(blank=True, default=1)

    class Meta:
        ordering = ["order"]

    def save(self, *args, **kwargs):
        if len(self.variants) > 4:  # Проверяем, что 4 элемента
            raise ValueError("Variants must have no more 4 elements")
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.topic} - {self.order}"

courses/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponseBadRequest
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from account.models import ProgressTask
from .models import Course, Topic, Task
import json


# Create your views here.
@login_required
def all_courses(request):
    courses = Course.objects.all()
    return render(request, 'courses/all_courses.html', {"courses": courses})


@login_required
def selected_course(request, course_id):
    course = Course.objects.prefetch_related("topics").filter(id=course_id).first()
    if not course:
        return render(request, "404.html", status=404)

    return render(request, "courses/selected_course.html", {"course": course})


@login_required
def selected_topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if not topic:
        return render(request, "404.html", status=404)

    tasks = Task.objects.filter(topic=topic_id).all()

    return render(request, "courses/selected_topic.html", {"topic": topic, "tasks": tasks})


@login_required
def task_detail(request, task_id):
    task = get_object_or_404(Task, id=task_id)
    topic = task.topic
    topic_tasks = Task.objects.filter(topic=topic).order_by('order')
    task_orders = list(topic_tasks)
    current_index = task_orders.index(task)

    # следующее задание в этой теме, если задания закончились, тогда следующая тема
    next_task = None
    next_topic = None
    if current_index + 1 < len(task_orders):
        next_task = task_orders[current_index + 1]
    else:
        next_topic = Topic.objects.filter(course=topic.course, order__gt=topic.order).order_by('order').first()

    task_data = {
        "id": task.id,
        "type": task.type,
        "question": task.question,
        "sentence_without_a_word": task.sentence_without_a_word,
        "variants": task.variants,
        "missed_word": task.missed_word,
        "sentence_for_ordering": task.sentence_for_ordering,
        "text_to_speech": task.text_to_speech,
        "audition_text": getattr(task, "audition_text", ""),
        "order": task.order,
        "mp3": task.mp3.url if task.mp3 else None
    }

    return render(request, 'courses/task_passing.html', {
        "task_json": json.dumps(task_data, ensure_ascii=False),
        "next_task_id": next_task.id if next_task else None,
        "next_topic_id": next_topic.id if next_topic else None,
    })


@require_POST
@login_required
def save_task_progress(request):
    task_id = request.POST.get("task_id")
    score = request.POST.get("score", 100.0)

    if not task_id:
        return JsonResponse({"error": "task_id is required"}, status=400)

    try:
        task = Task.objects.get(id=task_id)
    except Task.DoesNotExist:
        return JsonResponse({"error": "Task not found"}, status=404)

    progress, _ = ProgressTask.objects.get_or_create(user=request.user, task=task)
    progress.attempts += 1
    progress.score = float(score)
    progress.completed = True
    progress.save()

    return JsonResponse({"message": "Progress saved"})

templates/courses/all_courses.html
{% extends 'base.html' %}

{% block title %}Courses - LingoFlow{% endblock %}

{% block content %}

    <section class="courses-container">
        <h2>Explore English Courses</h2>
        <p>Choose your level and start learning today!</p>

        <div class="courses-list">
            {% for course in courses %}
                <div class="course-card">
                    <h3>{{ course.title }}</h3>
                    <p>{{ course.description }}</p>
                    <p><strong>Level:</strong> {{ course.get_difficulty_display }}</p>
                    <a href="{% url 'courses:selected_course' course.id %}" class="cta-button">View Course</a>
                </div>
            {% empty %}
                <p>No courses available.</p>
            {% endfor %}
        </div>
    </section>

{% endblock %}

templates/courses/selected_course.html
{% extends 'base.html' %}

{% block content %}
<div class="courses-container">
    <h2>{{ course.title }}</h2>
    <p>{{ course.description }}</p>
    <p><strong>Difficulty:</strong> {{ course.get_difficulty_display }}</p>

    <h3>Topics</h3>
    <ul class="topic-list">
        {% for topic in course.topics.all %}
        <li>
            <h4>{{ topic.title }}</h4>
            <a href="{% url 'courses:selected_topic' topic.id %}" class="cta-button">View Topic</a>
        </li>
        {% empty %}
        <p>No topics available.</p>
        {% endfor %}
    </ul>
</div>
{% endblock %}

templates/courses/selected_topic.html
{% extends 'base.html' %}
{% block title %}{{ topic.title }} - LingoFlow{% endblock %}

{% block content %}
<section class="topic-container" style="margin-top: 150px; margin-bottom: 200px;">
    <div class="topic-header">
        <h2>{{ topic.title }}</h2>
        <p class="explanation">{{ topic.explanation|safe }}</p>
    </div>

    <div class="task-list">
        <h3>Tasks</h3>
        <ul>
            {% for task in tasks %}
                <li class="task-item">
                    <a href="{% url 'courses:task_detail' task.id %}">{{ task.title }}</a>
                </li>
            {% empty %}
                <li>No tasks available for this topic yet.</li>
            {% endfor %}
        </ul>
    </div>
</section>
{% endblock %}

templates/courses/task_passing.html
{% extends 'base.html' %}
{% block title %}{{ task.title }} - LingoFlow{% endblock %}

{% block content %}
    <section class="topic-container" style="margin-top: 200px; margin-bottom: 150px;">
        <div class="topic-header">
            <h2>{{ task.title }}</h2>
            <p class="explanation">{{ task.question }}</p>
        </div>

        <div class="task-list">
            <div id="task-container"></div>
        </div>
    </section>

    <script>
        const task = {{ task_json|safe }};
        window.task = task

        {% if next_task_id %}
            window.nextTaskId = {{ next_task_id }};
            window.nextTaskUrl = "{% url 'courses:task_detail' next_task_id %}";
        {% else %}
            window.nextTaskId = null;
            {% if next_topic_id %}
                window.nextTopicId = {{ next_topic_id }};
                window.nextTopicUrl = "{% url 'courses:selected_topic' next_topic_id %}"
            {% else %}
                window.nextTopicId = null;
                window.nextTopicUrl = null;
                window.courses = "{% url 'courses:all_courses' %}"
            {% endif %}
        {% endif %}
    </script>

{% endblock %}